// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSelectController from "./auto_select_controller"
application.register("auto-select", AutoSelectController)

import CheckboxController from "./checkbox_controller"
application.register("checkbox", CheckboxController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)
