// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import AutoSelectController from "./auto_select_controller.js"
application.register("auto-select", AutoSelectController)

import CheckboxController from "./checkbox_controller.js"
application.register("checkbox", CheckboxController)

import ResetFormController from "./reset_form_controller.js"
application.register("reset-form", ResetFormController)
