Todo.create!(name: "I'm first!")
Todo.create!(name: "I'm second :(")
Todo.create!(name: "Nah, third")
Todo.create!(name: "I'm complete!", completed: true)
Todo.create!(name: "Me too, so what?", completed: true)
